//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordNet.Linq.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("38.192.14.25")]
        public string WordNet_ServerHost {
            get {
                return ((string)(this["WordNet_ServerHost"]));
            }
            set {
                this["WordNet_ServerHost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("49170")]
        public int WordNet_ServerPort {
            get {
                return ((int)(this["WordNet_ServerPort"]));
            }
            set {
                this["WordNet_ServerPort"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=38.192.14.25,49170;Initial Catalog=WordNet;Persist Security Info=True" +
            ";User ID=sa")]
        public string WordNetConnectionString {
            get {
                return ((string)(this["WordNetConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=38.192.14.25,49170;Initial Catalog=WordNet;Persist Security Info=True" +
            ";User ID=sa;Pooling=False;MultipleActiveResultSets=False;Connect Timeout=60;Encr" +
            "ypt=False;TrustServerCertificate=False")]
        public string WordNetConnectionString1 {
            get {
                return ((string)(this["WordNetConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=38.192.14.25,49170;Initial Catalog=WordNet;Persist Security Info=True" +
            ";User ID=sa;Pooling=False;MultipleActiveResultSets=False;Connect Timeout=60;Trus" +
            "tServerCertificate=False")]
        public string WordNetConnectionString2 {
            get {
                return ((string)(this["WordNetConnectionString2"]));
            }
        }
    }
}
